### ISSUE TITLE
[Feature Request] Disable XP drops

### ISSUE THREAD

**Issue by robmonte** [rsn-INVU/pre-eoc-xp-drops#1]
I know this request sounds weird, but I'd like to disable the actual XP drop. I like this plugin for the XP counter itself, but want the default XP drop animation instead. Any chance of adding a toggle to remove the XP text animation entirely and leave just the counter?

**Comment by rsn-INVU** [comment]
I'll look into it when I have the time! 
Also gonna be looking into fake xp drops and a 2012 toggle, so why not this as well I guess. Might end up being over Christmas though

**Comment by robmonte** [comment]
Thanks for considering it. Another thing may be changing the font to correspond to each time period you support?

**Comment by rsn-INVU** [comment]
Working on it now!
Your first request has been implemented (not live yet though, I'm doing some more things in parallell)

I just need to find the font that was used in 2011-2012 (hopefully I can :/ ), and then you'll see more options added.

**Comment by robmonte** [comment]
Thanks for adding this!!

**Comment by rsn-INVU** [comment]
no problem!
