### ISSUE TITLE
The Pre eoc plugin is not configuring, doesn't open the settings

### ISSUE THREAD

**Issue by Soffaah99** [rsn-INVU/pre-eoc-xp-drops#4]
The Pre eoc plugin is not configuring, doesn't open the settings, has to be fixed.

**Comment by rsn-INVU** [comment]
Copy of #3 

Let me know if it isn't the same problem, but I would assume it is. 
I'm hoping to have the spare time to work on a fix later this week 🤞

**Comment by Soffaah99** [comment]
I do think it's the same issue. Hoping you'll have time to fix this! :)
